### ISSUE TITLE
github handles

### ISSUE THREAD

**Issue by travula** [vlead/2017-summer-internship#1]
@kraghupathi 

Please create 2017-summer-interns team in vlead organization containing all the interns who have reported till now.

**Comment by travula** [comment]
@kraghupathi 

Please create a team vlead-staff with all the current members of VLEAD as part of vlead organization

**Comment by vleadadmin** [comment]
@travula : Created a group called 2017-summer-interns and added all the interns in it.

**Comment by kraghupathi** [comment]
@travula : Created a group called [vlead-staff](https://github.com/orgs/vlead/teams/vlead-staff) and added current VLEAD employees in it.
